name: Run tests

on: 
  pull_request:
    branches: [ master ]
    types: [ opened ]
  push:
    branches: [ master ]

jobs:
  test:
    name: test on PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run:
          npm install
      - run:
          npm run test